# Generated by Django 4.1 on 2024-06-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='address',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AddField(
            model_name='department',
            name='email',
            field=models.EmailField(default=' ', max_length=254),
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AddField(
            model_name='department',
            name='phone',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
