# Generated by Django 4.2.11 on 2024-06-07 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_news_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='slug',
        ),
    ]
