# Generated by Django 4.2.11 on 2024-06-07 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_person_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='positions',
        ),
    ]
