# Generated by Django 4.2.11 on 2024-06-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_department_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlifeevent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/', verbose_name='Изображение'),
        ),
    ]
