# Generated by Django 4.2.11 on 2024-06-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_studentlifeevent_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouthDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название отдела')),
                ('activities', models.TextField(verbose_name='Деятельность')),
            ],
        ),
    ]
