# Generated by Django 4.2.11 on 2024-06-07 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_youthdivision'),
    ]

    operations = [
        migrations.AddField(
            model_name='youthdivision',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='youth_division_head', to='core.person', verbose_name='Руководитель отдела'),
        ),
    ]
