# Generated by Django 4.2.11 on 2024-06-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_youthdivision_head'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название специальности')),
                ('duration', models.CharField(max_length=50, verbose_name='Срок обучения')),
                ('cost', models.CharField(max_length=100, verbose_name='Стоимость обучения')),
                ('exams', models.TextField(verbose_name='Экзамены')),
                ('budget_places', models.PositiveIntegerField(verbose_name='Количество бюджетных мест')),
                ('paid_places', models.CharField(max_length=4, verbose_name='Количество платных мест')),
                ('career', models.TextField(verbose_name='Карьера')),
            ],
        ),
    ]
