# Generated by Django 4.2.11 on 2024-06-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='description',
            field=models.TextField(default='', verbose_name='Описание специальности'),
        ),
    ]
