# Generated by Django 4.2.11 on 2024-06-09 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_specialty_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(default='Место проведения', max_length=255, verbose_name='Место проведения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='uril_speakers',
            field=models.URLField(blank=True, null=True, verbose_name='Докладчики'),
        ),
        migrations.AddField(
            model_name='event',
            name='url_conf',
            field=models.URLField(blank=True, null=True, verbose_name='Сайт конференцию'),
        ),
        migrations.AddField(
            model_name='project',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_head', to='core.person', verbose_name='Руководитель проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='project_participants', to='core.person', verbose_name='Участники'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(verbose_name='Описание мероприятия'),
        ),
    ]
