# Generated by Django 4.2.11 on 2024-06-09 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_event_place_event_uril_speakers_event_url_conf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='uril_speakers',
        ),
        migrations.AddField(
            model_name='event',
            name='organizer_contacts',
            field=models.TextField(blank=True, null=True, verbose_name='Контактная информация организаторов'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizing_committee',
            field=models.TextField(blank=True, null=True, verbose_name='Оргкомитет'),
        ),
        migrations.AddField(
            model_name='event',
            name='program_committee',
            field=models.TextField(blank=True, null=True, verbose_name='Программный комитет'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email для регистрации'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на регистрацию'),
        ),
        migrations.AddField(
            model_name='event',
            name='secretariat',
            field=models.TextField(blank=True, null=True, verbose_name='Секретариат'),
        ),
        migrations.AddField(
            model_name='event',
            name='sections',
            field=models.TextField(blank=True, null=True, verbose_name='Секции конференции'),
        ),
        migrations.AddField(
            model_name='event',
            name='speakers',
            field=models.ManyToManyField(blank=True, to='core.person', verbose_name='Докладчики'),
        ),
        migrations.AddField(
            model_name='event',
            name='url_speakers',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на докладчиков'),
        ),
        migrations.AlterField(
            model_name='event',
            name='url_conf',
            field=models.URLField(blank=True, null=True, verbose_name='Сайт конференции'),
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок презентации')),
                ('file', models.FileField(upload_to='presentations/', verbose_name='Файл презентации')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='core.event', verbose_name='Мероприятие')),
            ],
        ),
    ]
