# Generated by Django 4.2.11 on 2024-06-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_event_uril_speakers_event_organizer_contacts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок презентации'),
        ),
    ]
