# Generated by Django 4.2.11 on 2024-06-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_presentation_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='education_level',
            field=models.CharField(choices=[('B', 'Бакалавриат'), ('M', 'Магистратура'), ('P', 'Аспирантура')], default='B', max_length=1, verbose_name='Уровень образования'),
        ),
    ]
