# Generated by Django 4.2.11 on 2024-06-09 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_specialty_education_level'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Specialty',
            new_name='Speciality',
        ),
    ]
