# Generated by Django 4.2.11 on 2024-06-11 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_rename_specialty_speciality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(choices=[('B', 'Бакалавриат'), ('M', 'Магистратура'), ('S', 'ГИА')], max_length=1, verbose_name='Уровень образования')),
                ('form', models.CharField(choices=[('FT', 'Очная'), ('PT', 'Заочная'), ('FT_PT', 'Очно-заочная')], max_length=5, verbose_name='Форма обучения')),
                ('schedule_type', models.CharField(choices=[('interim', 'Промежуточная аттестация'), ('retake', 'Пересдача')], max_length=10, verbose_name='Тип расписания')),
                ('group', models.CharField(max_length=100, verbose_name='Группа')),
                ('course', models.PositiveIntegerField(verbose_name='Курс')),
                ('subject', models.CharField(max_length=255, verbose_name='Название предмета')),
                ('date', models.DateField(verbose_name='Дата')),
                ('semester', models.PositiveIntegerField(verbose_name='Семестр')),
                ('place', models.CharField(max_length=255, verbose_name='Место проведения')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.person', verbose_name='Преподаватель')),
            ],
        ),
    ]
