# Generated by Django 4.2.11 on 2024-06-11 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_schedule_assessment_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['course']},
        ),
    ]
