# Generated by Django 4.2.11 on 2024-06-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_schedule_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalEducationProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('program_director', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('program_type', models.CharField(max_length=100)),
                ('form_of_education', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('details', models.TextField()),
                ('application_link', models.URLField()),
                ('contact_info', models.CharField(max_length=100)),
            ],
        ),
    ]
