# Generated by Django 4.2.11 on 2024-06-11 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_additionaleducationprogram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaleducationprogram',
            name='application_link',
            field=models.URLField(verbose_name='Ссылка на подачу заявки'),
        ),
        migrations.AlterField(
            model_name='additionaleducationprogram',
            name='contact_info',
            field=models.CharField(max_length=100, verbose_name='Контактная информация'),
        ),
        migrations.AlterField(
            model_name='additionaleducationprogram',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость обучения'),
        ),
        migrations.AlterField(
            model_name='additionaleducationprogram',
            name='details',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='additionaleducationprogram',
            name='duration',
            field=models.CharField(max_length=100, verbose_name='Сроки проведения'),
        ),
        migrations.AlterField(
            model_name='additionaleducationprogram',
            name='form_of_education',
            field=models.CharField(max_length=100, verbose_name='Форма проведения'),
        ),
        migrations.AlterField(
            model_name='additionaleducationprogram',
            name='program_director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.person', verbose_name='Руководитель программы'),
        ),
        migrations.AlterField(
            model_name='additionaleducationprogram',
            name='program_type',
            field=models.CharField(max_length=100, verbose_name='Вид программы'),
        ),
        migrations.AlterField(
            model_name='additionaleducationprogram',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название программы'),
        ),
    ]
