# Generated by Django 4.2.11 on 2024-06-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='theme',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Тема'),
        ),
    ]
