# Generated by Django 4.2.11 on 2024-06-13 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_news_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='password_confirmation',
        ),
    ]
