# Generated by Django 4.2.11 on 2024-06-13 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_academiccouncil_options_alter_schedule_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionaleducationprogram',
            options={'verbose_name': 'Дополнительное образование', 'verbose_name_plural': 'Дополнительное образование'},
        ),
    ]
